Spring:
  #Application Properties
  application:
    name: blog-application

  #Datasource Properties
  datasource:
    url: jdbc:mysql://localhost:3306/blog-application?createDatabaseIfNotExist=true
    username: root
    password: root

  #JPA Details
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update